name: When a push occurs in the master branch, a private message is sent on the Whatsapp.
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install twilio
        run: pip install twilio
      - name: run code
        run: python main.py
        env:
          account_sid: ${{ add secret of account sid }}
          auth_token: ${{ add secret of auth token }}
          to_whatsapp_no: ${{ add secret of to_whatsapp_no }}
